name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Xmx3g -XX:MaxMetaspaceSize=512m"

    steps:
    - name: Setup Homebrew
      uses: Homebrew/actions/setup-homebrew@master
      id: set-up-homebrew

    - name: Install libpq
      run: brew install libpq

    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build Ktor Native
      uses: gradle/gradle-build-action@v2
      with:
        arguments: linkReleaseExecutableLinuxX64
              
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vergauwensimon/ktor-native-server:$(date +%s)
      
    - name: Docker Push
      run: docker push vergauwensimon/ktor-native-server
